dist: trusty

language: node_js
node_js:
  - 10

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.npm"

before_script:
  - "npm install -g bower grunt-cli karma"
  - "bower install" 

install:
  - npm install
  - grunt build
